/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef transfer_CONSTANTS_H
#define transfer_CONSTANTS_H

#include "transfer_types.h"



class transferConstants {
 public:
  transferConstants();

};

extern const transferConstants g_transfer_constants;



#endif
